name: chess_vision_pro
description: Advanced AR Chess Recorder
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  camera: ^0.11.0
  flutter_vision: ^1.1.4
  dartchess: ^0.11.1
  stockfish: ^1.2.0
  opencv_dart: ^1.0.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  http: ^1.1.0          # NEW: For downloading pieces
  path_provider: ^2.1.1 # NEW: For saving pieces

flutter:
  assets:
    - assets/models/best_float16.tflite
    - assets/models/labels.txt
    - assets/pieces/  # <--- THIS ADDS ALL YOUR CHESS PIECES